version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lavanda-telegram-serverless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1o3s4uuqcfxlw"
s3_prefix = "lavanda-telegram-serverless"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
